# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian12"
  config.vm.hostname = "debian12"
  config.vm.define "debian12"
  config.vm.network :private_network, ip: "192.168.56.12"
  config.vm.network "forwarded_port", guest: 22, host: 2112, id: "ssh"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "debian12"
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--cpus", 1]
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end
end

