all:
  hosts:
    alma:
      ansible_host: 192.168.56.10
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ./alma9/.vagrant/machines/alma9/virtualbox/private_key

    debian:
      ansible_host: 192.168.56.12
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ./debian12/.vagrant/machines/debian12/virtualbox/private_key
    
    rocky:
      ansible_host: 192.168.56.13
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ./rocky9/.vagrant/machines/rocky9/virtualbox/private_key
    
    ubuntu:
      ansible_host: 192.168.56.14
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ./ubuntu2204/.vagrant/machines/ubuntu2204/virtualbox/private_key

rhel_line:
  hosts:
    alma:
      ansible_host: 192.168.56.10
    rocky:
      ansible_host: 192.168.56.13

debian_line:
  hosts: 
    debian:
      ansible_host: 192.168.56.12
    ubuntu:
      ansible_host: 192.168.56.14
