---

- hosts: rhel_line
  tasks:
  - name: dnf update
    ansible.builtin.dnf:
      update_cache: true

- hosts: rhel_line
  tasks:
  - name: Install epel package
    become: true
    yum:
      name: epel-release
      state: present

- hosts: debian_line
  tasks:
  - name: apt update
    become: true
    ansible.builtin.apt:
      update_cache: true

- hosts: all
  tasks:
  - name: install apps
    become: true
    ansible.builtin.package:
      name:
      - curl
      - wget
      - rsync
      - vim
      - git
      - tmux
      - unzip
      state: latest
