all:
  hosts:
    alma:
      ansible_host: 192.168.56.10
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: '/home/gidra/Public/EDU.Self.Linux_Hardening/multi-machine/.vagrant/machines/alma/virtualbox/private_key'

    debian:
      ansible_host: 192.168.56.12
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: '/home/gidra/Public/EDU.Self.Linux_Hardening/multi-machine/.vagrant/machines/debian/virtualbox/private_key'
    
    rocky:
      ansible_host: 192.168.56.13
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: '/home/gidra/Public/EDU.Self.Linux_Hardening/multi-machine/.vagrant/machines/rocky/virtualbox/private_key'
    
    ubuntu:
      ansible_host: 192.168.56.14
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: '/home/gidra/Public/EDU.Self.Linux_Hardening/multi-machine/.vagrant/machines/ubuntu/virtualbox/private_key'

rhel_line:
  hosts:
    alma:
      ansible_host: 192.168.56.10
    rocky:
      ansible_host: 192.168.56.13

debian_line:
  hosts: 
    debian:
      ansible_host: 192.168.56.12
    ubuntu:
      ansible_host: 192.168.56.14

# ; alma ansible_ssh_host=127.0.0.1 ansible_ssh_port=2210 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/home/gidra/Public/EDU.Self.Linux_Hardening/multi-machine/.vagrant/machines/alma/virtualbox/private_key'
# ; debian ansible_ssh_host=127.0.0.1 ansible_ssh_port=2212 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/home/gidra/Public/EDU.Self.Linux_Hardening/multi-machine/.vagrant/machines/debian/virtualbox/private_key'
# ; rocky ansible_ssh_host=127.0.0.1 ansible_ssh_port=2213 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/home/gidra/Public/EDU.Self.Linux_Hardening/multi-machine/.vagrant/machines/rocky/virtualbox/private_key'
# ; ubuntu ansible_ssh_host=127.0.0.1 ansible_ssh_port=2214 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/home/gidra/Public/EDU.Self.Linux_Hardening/multi-machine/.vagrant/machines/ubuntu/virtualbox/private_key'
